# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        true

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false
    
test_functional:
  .settings:
    enabled_modules:
      - sfGuardAuth
      - fpPayment
      - fpPaymentCart
      - fpPaymentCheckout
      - fpPaymentPayPal
      - fpPaymentAuthorize
      - fpPaymentShipping
      - sfPhpunit

all:
  .settings:
    enabled_modules:
      - sfGuardAuth
      - fpPayment
      - fpPaymentCart
      - fpPaymentCheckout
      - fpPaymentPayPal
      - fpPaymentAuthorize
      - fpPaymentShipping
      
    # Form security secret (CSRF protection)
    csrf_secret:            f7cddcb2b8bb8a45471d43be1a31f647d900413d

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
    
    login_module:           sfGuardAuth
    login_action:           signin
    
    secure_module:          sfGuardAuth
    secure_action:          secure