<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
  /**
   * (non-PHPdoc)
   * @see BasesfGuardUser::setUp()
   */
  public function setUp()
  {
    parent::setUp();
    $fpPaymentProfileble = new Doctrine_Template_fpPaymentProfileble(array());
    $this->actAs($fpPaymentProfileble);
  }
}
