<?php

/**
 * fpPaymentShippingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class fpPaymentShippingTable extends PluginfpPaymentShippingTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object fpPaymentShippingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('fpPaymentShipping');
    }
}