<?php

/**
 * fpPaymentShippingDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class fpPaymentShippingDataTable extends PluginfpPaymentShippingDataTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object fpPaymentShippingDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('fpPaymentShippingData');
    }
}