all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=localhost;dbname=payment
      username: admin
      password: qwerty
      attributes:
        use_native_enum: true
#        use_dql_callbacks: true
        default_table_collate: utf8_unicode_ci
        default_table_charset: utf8
