<?php

/**
 * fpPaymentAuthorizeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class fpPaymentAuthorizeTable extends PluginfpPaymentAuthorizeTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object fpPaymentAuthorizeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('fpPaymentAuthorize');
    }
}