<?php

/**
 * fpPaymentCustomerProfileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class fpPaymentCustomerProfileTable extends PluginfpPaymentCustomerProfileTable
{

  /**
   * Returns an instance of this class.
   *
   * @return fpPaymentCustomerProfileTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('fpPaymentCustomerProfile');
  }
}