<?php

/**
 * fpPaymentOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class fpPaymentOrderTable extends PluginfpPaymentOrderTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object fpPaymentOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('fpPaymentOrder');
    }
}