<?php

/**
 * fpPaymentOrderItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class fpPaymentOrderItemTable extends PluginfpPaymentOrderItemTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object fpPaymentOrderItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('fpPaymentOrderItem');
    }
}