<?php

/**
 * fpPaymentTaxToDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class fpPaymentTaxToDataTable extends PluginfpPaymentTaxToDataTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object fpPaymentTaxToDataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('fpPaymentTaxToData');
    }
}