<?php

/**
 * fpPaymentTaxDataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class fpPaymentTaxDataTable extends PluginfpPaymentTaxDataTable
{

  /**
   * Returns an instance of this class.
   *
   * @return fpPaymentTaxDataTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('fpPaymentTaxData');
  }
}