Product:
  actAs:
    fpPaymentProduct: ~
    fpPaymentTaxable: ~
    fpPaymentShippable: ~
    Timestampable: ~
  columns:
#  relations:
#    Seller:
#      class: Seller
#      local: seller_id
#      onDelete: CASCADE

