<?php

/**
 * fpPaymentPaypalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class fpPaymentPaypalTable extends PluginfpPaymentPaypalTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object fpPaymentPaypalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('fpPaymentPaypal');
    }
}